# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8b1813cca6bd37c1244f543fef50af6d8abe27901a60b34708f0a1ce6d677ddb78f90842c1e48514a7f7a6a460d4adb8f49830fa47bb1337a89f686b1ee608c

test:
  secret_key_base: 101ea120b6d4889c08c98226e15d1e432ba6c2a8c16b43df89b5d56bdb470ebcc4292d7d2d14c01ec6fbf789832345fce80522c825a579e15187d776da9e06de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
